- hosts: 127.0.0.1
  connection: local

  vars:
    some_var: aqours

  tasks:
  - name: echo
    shell: |
      # here is comment
      echo hello
      echo world echo {{ some_var|upper }}
    register: result

  - name: debug
    shell: |
      echo {{ result.stdout_lines|quote }}

  - name: wait
    wait_for:
      port: 8080
      connect_timeout: 2
      delay: 2
      timeout: 30
      state: started

  - name: errors ignore
    shell: |
      /usr/bin/false
    ignore_errors: true

